name: CD

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy to prod
        run: |
          npm install
          npx serve /app/react-app -p 8080

  deploy-nonprod:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy to non-prod
        run: |
          npm install
          npx serve /app/react-app -p 8080
